server:
    interface: 0.0.0.0
    port: 53

    # Allow queries from Pi-hole network
    access-control: 172.20.0.0/24 allow
    access-control: 127.0.0.0/8 allow

    # Harden against spoofing
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    harden-below-nxdomain: yes

    # Privacy & SSL settings
    qname-minimisation: yes
    hide-identity: yes
    hide-version: yes
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

    # Query encoding & buffer
    use-caps-for-id: no
    edns-buffer-size: 1232

    # Prefetch cached elements
    prefetch: yes
    prefetch-key: yes

    # TTL & Serve-Expired settings
    cache-min-ttl: 3600
    cache-max-ttl: 86400
    serve-expired: yes
    serve-expired-ttl: 86400

    # Private addresses (RFC1918)
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8

forward-zone:
    name: "."
    forward-tls-upstream: yes

    # Cloudflare DoT
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com

    # Quad9 DoT
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net