services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Match the host path to the container path:
      - /home/admin/pihole:/root/docker
    environment:
      - DOCKGE_STACKS_DIR=/root/docker
      - DOCKGE_ENABLE_CONSOLE=true
      - PUID=1000
      - PGID=1000
